# Generated by Django 4.1 on 2023-04-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicResponse', '0002_alter_answer_ai_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='AI_answer',
            new_name='AIanswer',
        ),
    ]
